grid = Grid(6, 6)
grid.add_car(Car('hor', 2, 2, 2, red=True))
grid.add_car(Car('vert', 2, 0, 4))
grid.add_car(Car('vert', 2, 3, 4))
grid.add_car(Car('vert', 2, 4, 2))
grid.add_car(Car('vert', 3, 5, 1))
grid.add_car(Car('hor', 2, 2, 0))
grid.add_car(Car('hor', 2, 4, 0))
grid.add_car(Car('hor', 2, 1, 1))
grid.add_car(Car('hor', 2, 3, 1))
grid.add_car(Car('hor', 2, 0, 3))
grid.add_car(Car('hor', 2, 2, 3))
grid.add_car(Car('hor', 2, 4, 4))
grid.add_car(Car('hor', 2, 4, 5))